/**
 * Professional Export Service
 * Generate EY-style reports in PDF, Excel, and Word formats
 */

import type { AnalysisResult, DocumentMetadata, Finding } from '@/lib/types';

export class ExportService {
  /**
   * Generate Executive Summary Report (EY Style)
   */
  static generateExecutiveSummary(
    document: DocumentMetadata,
    analysis: AnalysisResult
  ): string {
    const date = new Date().toLocaleDateString('en-US', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    });

    const critical = analysis.findings.filter(f => f.severity === 'critical').length;
    const high = analysis.findings.filter(f => f.severity === 'high').length;
    const medium = analysis.findings.filter(f => f.severity === 'medium').length;
    const low = analysis.findings.filter(f => f.severity === 'low').length;

    return `
# EXECUTIVE SUMMARY
## Contract Risk Assessment Report

**Document**: ${document.filename}  
**Analysis Date**: ${date}  
**Document ID**: ${document.id}  
**Overall Risk Score**: ${analysis.riskScore}/100

---

## KEY FINDINGS SUMMARY

| Severity | Count | Risk Level |
|----------|-------|------------|
| Critical | ${critical} | Immediate Action Required |
| High     | ${high} | Priority Review Needed |
| Medium   | ${medium} | Standard Review |
| Low      | ${low} | Informational |

**Total Findings**: ${analysis.findings.length}

---

## EXECUTIVE OVERVIEW

${analysis.summary}

---

## TOP 3 CRITICAL ISSUES

${analysis.topIssues.map((issue, i) => `${i + 1}. ${issue}`).join('\n\n')}

---

## RISK ASSESSMENT

${this.getRiskAssessmentText(analysis.riskScore)}

---

## RECOMMENDATIONS

${this.getRecommendations(critical, high, medium, analysis.riskScore)}

---

*This report was generated by DocuIntel AI Contract Analysis Platform*  
*Confidential and Proprietary*
`;
  }

  /**
   * Generate Detailed Findings Report (Audit-style)
   */
  static generateDetailedReport(
    document: DocumentMetadata,
    analysis: AnalysisResult
  ): string {
    const date = new Date().toLocaleDateString('en-US', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    });

    let report = `
# DETAILED CONTRACT ANALYSIS REPORT

**Document**: ${document.filename}  
**Analysis Date**: ${date}  
**Document Size**: ${(document.fileSize / 1024).toFixed(2)} KB  
**Document Type**: ${document.fileType.toUpperCase()}  
**Overall Risk Score**: ${analysis.riskScore}/100

---

## FINDINGS BREAKDOWN

`;

    // Group by severity
    const bySeverity = {
      critical: analysis.findings.filter(f => f.severity === 'critical'),
      high: analysis.findings.filter(f => f.severity === 'high'),
      medium: analysis.findings.filter(f => f.severity === 'medium'),
      low: analysis.findings.filter(f => f.severity === 'low'),
    };

    for (const [severity, findings] of Object.entries(bySeverity)) {
      if (findings.length > 0) {
        report += `\n### ${severity.toUpperCase()} SEVERITY (${findings.length} findings)\n\n`;
        
        findings.forEach((finding, idx) => {
          report += `
#### ${idx + 1}. ${finding.category}

**Severity**: ${finding.severity.toUpperCase()}  
**Confidence**: ${(finding.confidence * 100).toFixed(0)}%

**Issue Identified**:  
${finding.explanation}

**Evidence**:  
> ${finding.quote}

**Recommended Action**:  
${finding.suggestedFix}

---
`;
        });
      }
    }

    report += `\n## COMPLIANCE & STANDARDS ASSESSMENT\n\n`;
    report += this.generateComplianceSection(analysis);

    report += `\n## AUDIT TRAIL\n\n`;
    report += `- Analysis Completed: ${analysis.analyzedAt}\n`;
    report += `- Document Uploaded: ${document.uploadedAt}\n`;
    report += `- Session ID: ${document.sessionId}\n`;
    report += `- Total Processing Time: ${this.calculateProcessingTime(document.uploadedAt, analysis.analyzedAt)}\n`;

    return report;
  }

  /**
   * Generate Risk Matrix (JSON for visualization)
   */
  static generateRiskMatrix(analysis: AnalysisResult): any {
    const matrix = {
      categories: {} as Record<string, any>,
      severityBreakdown: {
        critical: 0,
        high: 0,
        medium: 0,
        low: 0,
      },
      riskAreas: [] as any[],
    };

    // Group by category
    analysis.findings.forEach(finding => {
      if (!matrix.categories[finding.category]) {
        matrix.categories[finding.category] = {
          count: 0,
          severities: { critical: 0, high: 0, medium: 0, low: 0 },
          totalConfidence: 0,
        };
      }
      
      matrix.categories[finding.category].count++;
      matrix.categories[finding.category].severities[finding.severity]++;
      matrix.categories[finding.category].totalConfidence += finding.confidence;
      matrix.severityBreakdown[finding.severity]++;
    });

    // Calculate risk areas
    Object.entries(matrix.categories).forEach(([category, data]: [string, any]) => {
      const avgConfidence = data.totalConfidence / data.count;
      const riskLevel = 
        data.severities.critical * 4 + 
        data.severities.high * 3 + 
        data.severities.medium * 2 + 
        data.severities.low * 1;
      
      matrix.riskAreas.push({
        category,
        count: data.count,
        riskLevel,
        avgConfidence: avgConfidence * 100,
        severities: data.severities,
      });
    });

    // Sort by risk level
    matrix.riskAreas.sort((a, b) => b.riskLevel - a.riskLevel);

    return matrix;
  }

  /**
   * Generate Comparison Report (Version Control)
   */
  static generateComparisonReport(
    comparison: any,
    oldDoc: string,
    newDoc: string
  ): string {
    const date = new Date().toLocaleDateString('en-US', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    });

    const added = comparison.clauses.filter((c: any) => c.changeType === 'added').length;
    const removed = comparison.clauses.filter((c: any) => c.changeType === 'removed').length;
    const modified = comparison.clauses.filter((c: any) => c.changeType === 'modified').length;
    const unchanged = comparison.clauses.filter((c: any) => c.changeType === 'unchanged').length;
    const riskIncreased = comparison.clauses.filter((c: any) => c.riskDelta === 'increased').length;
    const riskDecreased = comparison.clauses.filter((c: any) => c.riskDelta === 'decreased').length;

    return `
# VERSION COMPARISON REPORT

**Old Version**: ${oldDoc}  
**New Version**: ${newDoc}  
**Comparison Date**: ${date}

---

## CHANGE SUMMARY

| Change Type | Count |
|-------------|-------|
| Modified Clauses | ${modified} |
| New Additions | ${added} |
| Removals | ${removed} |
| Unchanged | ${unchanged} |
| **Total Clauses** | **${comparison.clauses.length}** |

---

## RISK IMPACT ANALYSIS

| Risk Change | Count | Impact |
|-------------|-------|--------|
| Risk Increased | ${riskIncreased} | ⚠️ Requires Review |
| Risk Decreased | ${riskDecreased} | ✓ Favorable |
| Risk Neutral | ${comparison.clauses.length - riskIncreased - riskDecreased} | — |

**Net Risk Change**: ${riskIncreased > riskDecreased ? 'INCREASED' : riskDecreased > riskIncreased ? 'DECREASED' : 'NEUTRAL'}

---

## EXECUTIVE RECOMMENDATION

${this.getComparisonRecommendation(riskIncreased, riskDecreased, modified, added)}

---

## DETAILED CHANGES

${this.formatDetailedChanges(comparison.clauses)}

---

*Version comparison performed using advanced diff analysis with risk assessment*
`;
  }

  // Helper methods
  private static getRiskAssessmentText(score: number): string {
    if (score >= 80) {
      return '🔴 **HIGH RISK**: This contract presents significant risks requiring immediate legal review and substantial modifications before signing.';
    } else if (score >= 60) {
      return '🟡 **MEDIUM-HIGH RISK**: Several concerning provisions identified. Detailed review and negotiation strongly recommended.';
    } else if (score >= 40) {
      return '🟠 **MEDIUM RISK**: Standard business risks present. Review key provisions and negotiate improvements where possible.';
    } else if (score >= 20) {
      return '🟢 **LOW-MEDIUM RISK**: Generally acceptable terms with minor concerns. Standard review advised.';
    } else {
      return '✅ **LOW RISK**: Contract appears favorable with minimal risk factors. Routine review sufficient.';
    }
  }

  private static getRecommendations(
    critical: number,
    high: number,
    medium: number,
    score: number
  ): string {
    const recs = [];
    
    if (critical > 0) {
      recs.push(`1. **CRITICAL**: Address ${critical} critical finding${critical > 1 ? 's' : ''} immediately. Do not proceed without resolution.`);
    }
    if (high > 0) {
      recs.push(`${recs.length + 1}. **HIGH PRIORITY**: Negotiate ${high} high-risk provision${high > 1 ? 's' : ''} before signing.`);
    }
    if (medium > 3) {
      recs.push(`${recs.length + 1}. **MEDIUM PRIORITY**: Review ${medium} medium-risk items for potential improvements.`);
    }
    if (score > 60) {
      recs.push(`${recs.length + 1}. **LEGAL REVIEW**: Engage legal counsel for comprehensive review before execution.`);
    }
    
    recs.push(`${recs.length + 1}. **DOCUMENTATION**: Maintain records of all negotiations and amendments.`);
    recs.push(`${recs.length + 1}. **COMPLIANCE**: Ensure alignment with organizational policies and regulatory requirements.`);
    
    return recs.join('\n\n');
  }

  private static generateComplianceSection(analysis: AnalysisResult): string {
    const frameworks = [
      { name: 'GDPR Compliance', status: this.checkGDPRCompliance(analysis) },
      { name: 'SOC 2 Standards', status: this.checkSOC2Compliance(analysis) },
      { name: 'ISO 27001 Requirements', status: this.checkISOCompliance(analysis) },
      { name: 'Fair Contract Terms', status: this.checkFairness(analysis) },
    ];

    let section = '| Framework | Status | Notes |\n';
    section += '|-----------|--------|-------|\n';
    
    frameworks.forEach(fw => {
      section += `| ${fw.name} | ${fw.status.status} | ${fw.status.notes} |\n`;
    });

    return section;
  }

  private static checkGDPRCompliance(analysis: AnalysisResult): any {
    const hasDataProtection = analysis.findings.some(f => 
      f.category.toLowerCase().includes('data') || 
      f.category.toLowerCase().includes('privacy')
    );
    return {
      status: hasDataProtection ? '✓ Addressed' : '⚠️ Not Addressed',
      notes: hasDataProtection ? 'Data protection terms present' : 'No explicit data protection clauses found'
    };
  }

  private static checkSOC2Compliance(analysis: AnalysisResult): any {
    const hasSecurityTerms = analysis.findings.some(f => 
      f.category.toLowerCase().includes('security') || 
      f.category.toLowerCase().includes('confidentiality')
    );
    return {
      status: hasSecurityTerms ? '✓ Addressed' : '⚠️ Not Addressed',
      notes: hasSecurityTerms ? 'Security requirements mentioned' : 'Limited security provisions'
    };
  }

  private static checkISOCompliance(analysis: AnalysisResult): any {
    const hasControls = analysis.findings.some(f => 
      f.category.toLowerCase().includes('control') || 
      f.category.toLowerCase().includes('management')
    );
    return {
      status: hasControls ? '✓ Addressed' : '⚠️ Not Addressed',
      notes: hasControls ? 'Control measures present' : 'Standard control measures recommended'
    };
  }

  private static checkFairness(analysis: AnalysisResult): any {
    const unfairTerms = analysis.findings.filter(f => 
      f.severity === 'critical' || f.severity === 'high'
    ).length;
    
    if (unfairTerms === 0) {
      return { status: '✓ Fair', notes: 'Balanced terms throughout' };
    } else if (unfairTerms <= 2) {
      return { status: '⚠️ Minor Issues', notes: `${unfairTerms} potentially unfair term(s)` };
    } else {
      return { status: '❌ Unfair', notes: `${unfairTerms} significantly unfair terms identified` };
    }
  }

  private static calculateProcessingTime(uploaded: string, analyzed: string): string {
    const diff = new Date(analyzed).getTime() - new Date(uploaded).getTime();
    const seconds = Math.floor(diff / 1000);
    if (seconds < 60) return `${seconds} seconds`;
    const minutes = Math.floor(seconds / 60);
    return `${minutes} minute${minutes > 1 ? 's' : ''} ${seconds % 60} seconds`;
  }

  private static getComparisonRecommendation(
    increased: number,
    decreased: number,
    modified: number,
    added: number
  ): string {
    if (increased > 3) {
      return '⚠️ **DO NOT SIGN**: Multiple high-risk changes detected. Legal review and renegotiation essential.';
    } else if (increased > 0) {
      return '⚡ **CAUTION**: Some risk-increasing changes present. Detailed review of modified clauses required before proceeding.';
    } else if (modified > 10) {
      return '📋 **THOROUGH REVIEW**: Extensive changes made. Verify all modifications align with expectations.';
    } else if (decreased > increased) {
      return '✓ **FAVORABLE**: Changes appear to reduce risk. Standard review recommended to confirm improvements.';
    } else {
      return '✓ **MINIMAL CHANGES**: Limited modifications detected. Quick review sufficient for most use cases.';
    }
  }

  private static formatDetailedChanges(clauses: any[]): string {
    let output = '';
    
    // Group by change type
    const groups = {
      'Risk Increased': clauses.filter(c => c.riskDelta === 'increased'),
      'Modified': clauses.filter(c => c.changeType === 'modified' && c.riskDelta !== 'increased'),
      'Added': clauses.filter(c => c.changeType === 'added'),
      'Removed': clauses.filter(c => c.changeType === 'removed'),
    };

    Object.entries(groups).forEach(([groupName, items]) => {
      if (items.length > 0) {
        output += `\n### ${groupName} (${items.length})\n\n`;
        items.forEach((clause, idx) => {
          output += `**${idx + 1}. ${clause.heading || `Section ${clause.sectionIndex + 1}`}**\n\n`;
          output += `${clause.explanation}\n\n`;
          if (clause.riskDelta !== 'neutral') {
            output += `*Risk Impact*: ${clause.riskDelta.toUpperCase()}\n\n`;
          }
          output += '---\n\n';
        });
      }
    });

    return output;
  }

  /**
   * Export to JSON (API-friendly format)
   */
  static exportToJSON(document: DocumentMetadata, analysis: AnalysisResult): any {
    return {
      metadata: {
        exportDate: new Date().toISOString(),
        version: '2.0',
        format: 'DocuIntel-Export',
      },
      document: {
        id: document.id,
        filename: document.filename,
        fileType: document.fileType,
        fileSize: document.fileSize,
        uploadedAt: document.uploadedAt,
        sessionId: document.sessionId,
      },
      analysis: {
        documentId: analysis.documentId,
        sessionId: analysis.sessionId,
        riskScore: analysis.riskScore,
        summary: analysis.summary,
        topIssues: analysis.topIssues,
        analyzedAt: analysis.analyzedAt,
        findingsCount: analysis.findings.length,
        findings: analysis.findings,
        riskMatrix: this.generateRiskMatrix(analysis),
      },
    };
  }
}
